### ISSUE TITLE
Processors are not called on LogRecords prior to calling Handler filter methods

### ISSUE THREAD

**Issue by ssanderson** [mitsuhiko/logbook#112]
I have an application in which we use a Processor to conditionally add information to LogRecords.  Later on in our pipeline, we filter LogRecords based on information that was added by the Processor.  This pattern no longer works as of https://github.com/mitsuhiko/logbook/commit/43a63589b318482edbc990faa079017669b0ff36, because that change moves the check on `handler.filter` to before the call to `self.process_record`.  

A simple fix would be to move the call to `process_record` to happen prior to the filter check in `RecordDispatcher.call_handlers`, but it's unclear to me whether that's correct because the current implementation is explicitly short-circuiting when `blackhole = True`, presumably to avoid doing unncessary processing.

**Comment by jikamens** [comment]
(bump) We just upgraded logbook to 0.9.0, not realizing that this hadn't been fixed yet, and it broke our app logging again. *sigh* Any chance we can get some attention to this?

**Comment by vmalloc** [comment]
I can try and get to it today or tomorrow. A PR with a failing test would
help a lot.

**Comment by vmalloc** [comment]
Ok, I pushed a naive fix for this, which basically means:

* Handlers which are black holes without filters will avoid heavy init and discard immediately
* Handlers which are black holes *with* filters will first heavy initalize, then filter, and then discard if the filter matches
* All other cases will first heavy init, then filter as requested.

The `shouldHandle` method remains the fast way to discard records while avoiding heavy init.

Before releasing a version I would like some more people to weigh in on this and make sure it makes sense. @brainstorm, what do you say? @grzn / @yalon , have any inputs?

**Comment by vmalloc** [comment]
PS the commit in question is ee18350754ad81eded1bcea18b94171c892c8f83

**Comment by vmalloc** [comment]
Also pushed 5934e94 to fix a typo

**Comment by jikamens** [comment]
>The `shouldHandle` method remains the fast way to discard records while avoiding heavy init.

I don't see "shouldHandle" documented anywhere. "git grep -i shouldHandle" doesn't match anything. Could you elaborate on this?

**Comment by vmalloc** [comment]
@jikamens it is not so publicly known and is a relatively old feature that was there before as well. It is defined here: https://github.com/mitsuhiko/logbook/blob/master/logbook/handlers.py#L198

**Comment by jikamens** [comment]
>it is not so publicly known and is a relatively old feature that was there before as well. It is defined here: https://github.com/mitsuhiko/logbook/blob/master/logbook/handlers.py#L198

Ah, so when you wrote `shouldHandle`, you meant to write `should_handle`?

Maybe this feature should be documented somewhere?

**Comment by jikamens** [comment]
I don't think `should_handle` is going to work for us. Our Processor is changing the record in a way that is subsequently used by the filter to decide how to handle it. That means that `should_handle` will have the same problem as we're having now with Logbook 0.9.0 -- when it gets called, our Processor will not yet have been called, so the data we need to decide whether to handle the record won't be available.

It would therefore be helpful to us if this fix could be shipped in a PyPI release.

**Comment by vmalloc** [comment]
I must admit I'm confused. Are the two fixes working for you or aren't they?

**Comment by jikamens** [comment]
>I must admit I'm confused. Are the two fixes working for you or aren't they?

I had not tested them.

I was waiting for the feedback from others that you requested above ("Before releasing a version I would like some more people to weigh in on this and make sure it makes sense. @brainstorm, what do you say? @grzn / @yalon , have any inputs?") and for a release containing them, which I got the impression, from the comment I just quoted, would be forthcoming.

I just tested these changes now and it does indeed solve our problem.

**Comment by vmalloc** [comment]
Ok, lacking any other comments I will release a minor version containing this fix. Thanks!

**Comment by vmalloc** [comment]
Released 0.9.1 with the fix. Please let me know if you have any issues with it.
