### ISSUE TITLE
Remove the default global handler

### ISSUE THREAD

**Issue by vmalloc** [mitsuhiko/logbook#141]
This is a tough one.

One of the problems with Logbook today that is hindering its adoption is, in my opinion, the default global handler.

While very useful for quick apps or webapps, it is an annoyance to library developers -- each library explicitly or implicitly using Logbook means output to stderr *by default*.

Given the fact that setting up logbook is so easy (especially compared to `basicConfig`), I think dropping the default global handler is a wise move. Application seeking to add it back need a single line in their `if __name__ == 'main'` section, while libraries can rest assured that they don't litter the screen by default.

However I won't go forward making the change before I hear some more opinions about it - @brainstorm or anyone else, please let me know what you think...

**Comment by brainstorm** [comment]
That indeed sounds like a good move, specially if we want third party libs to start using Logbook more. As long as the docs are clear on those two use cases, I see no reason to go for it. Well thought @vmalloc!

**Comment by vmalloc** [comment]
@brainstorm who else do we want to involve in this decision? I'm trying to avoid a massive rage once we bump a version with this change...

**Comment by brainstorm** [comment]
Other than upstream's @mitsuhiko, who I guess is packed right now with other projects and decisions, I cannot think of anyone else...

**Comment by vmalloc** [comment]
I posted a message in `#pocoo`, but nobody seemed to respond, so I guess I'll just make the change if nobody objects within a few days...

**Comment by brainstorm** [comment]
:+1:

**Comment by vmalloc** [comment]
@brainstorm why close the issue?

**Comment by brainstorm** [comment]
Oops, sorry, my bad :-S

**Comment by brainstorm** [comment]
So this one got in for 0.11 at the end, right?

**Comment by vmalloc** [comment]
To 0.10. Forgot to close :-)
