### ISSUE TITLE
Skip build option

### ISSUE THREAD

**Issue by RazerM** [mitsuhiko/logbook#149]
Currently, only certain exceptions are caught before trying to build without speedups. Something in my environment causes `ValueError` to be raised, which means I can't install logbook.

Perhaps there should be a way to force skip of the compile step, or `ValueError` can be checked and raise `BuildFailed`.

```
Collecting logbook
  Using cached Logbook-0.10.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in c:\python34\lib\site-packages (from logbook)
Installing collected packages: logbook
  Running setup.py install for logbook
    Complete output from command c:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\FRAZER~1\\AppData\\Local\\Temp\\pip-build-kco3r3mt\\logbook\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\FRAZER~1\AppData\Local\Temp\pip-ymatx5nb-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\logbook
    copying logbook\base.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\compat.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\concurrency.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\handlers.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\helpers.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\more.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\notifiers.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\queues.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\ticketing.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\_fallback.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\_termcolors.py -> build\lib.win-amd64-3.4\logbook
    copying logbook\__init__.py -> build\lib.win-amd64-3.4\logbook
    running build_ext
    building 'logbook._speedups' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\FRAZER~1\AppData\Local\Temp\pip-build-kco3r3mt\logbook\setup.py", line 133, in <module>
        run_setup(True)
      File "C:\Users\FRAZER~1\AppData\Local\Temp\pip-build-kco3r3mt\logbook\setup.py", line 124, in run_setup
        **extra
      File "c:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\Python34\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\Python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\Python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "c:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\FRAZER~1\AppData\Local\Temp\pip-build-kco3r3mt\logbook\setup.py", line 83, in run
        build_ext.run(self)
      File "c:\Python34\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "C:\Users\FRAZER~1\AppData\Local\Temp\pip-build-kco3r3mt\logbook\setup.py", line 89, in build_extension
        build_ext.build_extension(self, ext)
      File "c:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
        depends=ext.depends)
      File "c:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "c:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\Python34\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "c:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']
```

**Comment by RazerM** [comment]
I think `setup.py` should catch `ValueError` at least, and possibly even catch bare `Exception` (!). There's a completely valid way to continue without speedups. I'm hesitant to add logbook as a dependency if pip install might fail for the end user.

**Comment by vmalloc** [comment]
@RazerM what version of setuptools are you using?

**Comment by RazerM** [comment]
I had v12.x then had same problem after upgrading to setuptools v18.4. To be clear, I'm able to get a compiler set up (as annoying as it is) and then install it fine, but the install shouldn't fail if the build fails.

**Comment by vmalloc** [comment]
@RazerM usually the install shouldn't fail if the build fails - some of us are installing logbook without building it...

It is very possible that this is a Windows-specific issue -- we have several of those, and not enough people to look into them :-(

**Comment by RazerM** [comment]
@vmalloc Is there a reason you don't want to catch `ValueError` at [setup.py line 84](https://github.com/mitsuhiko/logbook/blob/277d0ddfeeee79a88442f05d9145392b0953b2fb/setup.py#L84)?

**Comment by vmalloc** [comment]
Well, I don't like catching generic Python exceptions (which could stem from a very wide multitude of reasons) in setup.py. That's casting a very wide net that could hide real issues. We've had several of these before, among else causing us to realize that the extension is not built at all by anyone... If it were a specific exception indicating a specific problem I wouldn't have a problem with it.

**Comment by RazerM** [comment]
I see your point. Would you be interested in a pull request to set up AppVeyor testing and building of wheels? Then pip can install from wheels on Windows.

**Comment by brainstorm** [comment]
From my point of view, that would be a really welcome contribution since we have pending issues we cannot act upon easily regarding windows support :)

**Comment by vmalloc** [comment]
Also totally agree with @brainstorm . Any help on that front would be greatly appreciated.

**Comment by vmalloc** [comment]
@RazerM I see the failure you've encountered on Travis. Looking into it. It's on 2.6 only so ignore it for now.

**Comment by RazerM** [comment]
@vmalloc I fixed it by importing pip directly for `pip.main()`

**Comment by RazerM** [comment]
@vmalloc Before I look into it, any idea what's [causing this error](https://ci.appveyor.com/project/RazerM/logbook/build/1.0.11/job/1e1oesubpr046fur) in `test_basic_ticketing`? I can't reproduce on my own Windows machine.

**Comment by vmalloc** [comment]
I have no immediate explanation. Looking at the code this might happen when timestamps get broken (the db fetches issues by last occurrence, so if for some reason two issues get the same timestamp it might happen). Doesn't reproduce on my end either...

**Comment by RazerM** [comment]
Ah yes, the timestamps are equal for the tickets.
