### ISSUE TITLE
Multiple processes, same log file?

### ISSUE THREAD

**Issue by josefdlange** [mitsuhiko/logbook#153]
I'm experiencing some interesting behavior using a `RotatingFileHandler` with multiple processes -- one running an application server and the others are workers. All are running on the same machine. It seems to me that as each process tries to start, it tries to grab the log file defined in my config, and as each does, it possibly moves the existing `application.log` and creates a new one. What ends up happening (and this is only _some_ of the time) is there could be `application.log`, `application.log.1`, and `application.log.2` all writing to the same file.

Any thoughts on how I might remedy this?

**Comment by vmalloc** [comment]
I don't think there's an easy solution to this. The rule of thumb is that once you go for multiple processes you should leave the reigns to something that was designed to do what you're asking for, like syslog.

**Comment by josefdlange** [comment]
That's reasonable. I've been wary of using syslog since my application's logging is noisy enough, but I guess that's my own problem :stuck_out_tongue:. Thanks for the tips and I think I'll look into syslog and then some of the neat aggregation tools that are out there.
